apiVersion: v1
kind: Service
metadata:
  name: elastic-search-headless
spec:
  selector:
    app: elastic-search
  clusterIP: None
  ports:
    - name: communication
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
    - name: metrics
      port: 9114
      targetPort: 9114